---
- name: Install Nomad
  hosts: all
  become: true

  tasks:
    - name: Install unzip
      package:
        name:
          - unzip
        state: present

    - name: Download Nomad
      get_url:
        url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
        dest: "/tmp/nomad.zip"

    - name: Unzip Nomad
      unarchive:
        src: "/tmp/nomad.zip"
        dest: "/usr/local/bin"
        remote_src: yes
        extra_opts: "--strip-components=1"

    - name: Set Nomad permissions
      file:
        path: "/usr/local/bin/nomad"
        mode: "0755"
        state: file

    - name: Create Nomad config directory
      file:
        path: "/etc/nomad.d"
        state: directory
        mode: "0755"

    - name: Create Nomad data directory
      file:
        path: "/var/nomad"
        state: directory
        mode: "0755"

    - name: Create Nomad systemd service
      template:
        src: "templates/nomad.service.j2"
        dest: "/etc/systemd/system/nomad.service"
      notify:
        - Reload systemd

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes
        state: restarted
        name: nomad
